### ISSUE TITLE
docs: alarms

### ISSUE THREAD

**Issue by batonac** [cmcornish/Pico-Green-Clock#12]
Thanks for this great firmware! Most of the functions are fairly self-explanatory, but I can't figure out how to set the alarms on the regular Pico.

**Comment by batonac** [comment]
found it! long-press top button. thanks again!

**Comment by cmcornish** [comment]
Hi Batonac,
Sorry for the delay in responding, I haven't received any notifications and not visited the site.
I think this is unchanged from the original astlouys documentation. The original code had a pdf document that was very good. I have wondered about updating this bur resisted so that the code can be re-integrated in. I have tried to cover most of the major points in the release notes.
I'm glad you worked it out.
Regards,
Chris.

**Comment by batonac** [comment]
No sweat ~ Thanks so much!
